package me.matl114.matlib.nmsMirror;

import com.mojang.serialization.DataResult;
import io.papermc.paper.datacomponent.item.CustomModelData;
import me.matl114.matlib.utils.reflect.ByteCodeUtils;

public interface Import {
    String Tag = "Lnet/minecraft/nbt/Tag;";
    String ListTag = "Lnet/minecraft/nbt/ListTag;";
    String CompoundTag = "Lnet/minecraft/nbt/CompoundTag;";
    String NumericTag = "Lnet/minecraft/nbt/NumericTag;";
    String Item = "Lnet/minecraft/world/item/Item;";
    String Block = "Lnet/minecraft/world/level/block/Block;";
    String ItemStack = "Lnet/minecraft/world/item/ItemStack;";
    String ItemLike = "Lnet/minecraft/world/level/ItemLike;";
    String ResourceLocation = "Lnet/minecraft/resources/ResourceLocation;";
    String DataComponentType = "Lnet/minecraft/core/component/DataComponentType;";
    String DataComponentMap = "Lnet/minecraft/core/component/DataComponentMap;";
//    String CraftPersistentDataContainer = "Lorg/bukkit/craftbukkit/persistence/CraftPersistentDataContainer;";
    String BlockPos = "Lnet/minecraft/core/BlockPos;";
    String Vec3i = "Lnet/minecraft/core/Vec3i;";
    String BlockState = "Lnet/minecraft/world/level/block/state/BlockState;";
    String Direction = "Lnet/minecraft/core/Direction;";
    String LevelAccessor = "Lnet/minecraft/world/level/LevelAccessor;";
    String ServerLevel = "Lnet/minecraft/server/level/ServerLevel;";
    String Level = "Lnet/minecraft/world/level/Level;";
    String ChunkStatus = "Lnet/minecraft/world/level/chunk/status/ChunkStatus;";
    String BlockEntity = "Lnet/minecraft/world/level/block/entity/BlockEntity;";
    String StateProperty = "Lnet/minecraft/world/level/block/state/properties/Property;";
    String RandomSource = "Lnet/minecraft/util/RandomSource;";
    String Entity = "Lnet/minecraft/world/entity/Entity;";
    String Container = "Lnet/minecraft/world/Container;";
    String Player = "Lnet/minecraft/world/entity/player/Player;";
    String HopperBlockEntity = "Lnet/minecraft/world/level/block/entity/HopperBlockEntity;";
    String CraftPersistentDataContainer = "Lorg/bukkit/craftbukkit/persistence/CraftPersistentDataContainer;";
    String ChatComponent = "Lnet/minecraft/network/chat/Component;";
    String ComponentSerialization = "Lnet/minecraft/network/chat/ComponentSerialization;";
    String ChannelInitializeListener = "Lio/papermc/paper/network/ChannelInitializeListener;";
    String Packet = "Lnet/minecraft/network/protocol/Packet;";
    String PacketListener = "Lnet/minecraft/network/PacketListener;";
    String FriendlyByteBuf = "Lnet/minecraft/network/FriendlyByteBuf;";
    String PacketSendListener = "Lnet/minecraft/network/PacketSendListener;";
    String Connection = "Lnet/minecraft/network/Connection;";
    String DataSource = "Lnet/minecraft/network/chat/contents/data/DataSource;";
    String AdventureComponent = "Lio/papermc/paper/adventure/AdventureComponent;";
    String MutableComponent = "Lnet/minecraft/network/chat/MutableComponent;";
    String Style = "Lnet/minecraft/network/chat/Style;";
    String ChatComponentSerializer = "Lnet/minecraft/network/chat/Component$Serializer;";
    String TextColor = "Lnet/minecraft/network/chat/TextColor;";
    String ClickEvent = "Lnet/minecraft/network/chat/ClickEvent;";
    String ClickEventAction = "Lnet/minecraft/network/chat/ClickEvent$Action;";
    String HoverEvent = "Lnet/minecraft/network/chat/HoverEvent;";
    String HoverEventAction = "Lnet/minecraft/network/chat/HoverEvent$Action;";
    String HoverEventItemStackInfo = "Lnet/minecraft/network/chat/HoverEvent$ItemStackInfo;";
    String HoverEventShowItem = "Lnet/minecraft/network/chat/HoverEvent$ShowItem;";
    String HoverEventShowText = "Lnet/minecraft/network/chat/HoverEvent$ShowText;";
    String ComponentContents = "Lnet/minecraft/network/chat/ComponentContents;";
    String ScoreContents = "Lnet/minecraft/network/chat/contents/ScoreContents;";
    String NbtContents = "Lnet/minecraft/network/chat/contents/NbtContents;";
    String TranslatableContents = "Lnet/minecraft/network/chat/contents/TranslatableContents;";
    String SelectorContents = "Lnet/minecraft/network/chat/contents/SelectorContents;";
    //String PlainTextContents = "Lnet/minecraft/network/chat/contents/PlainTextContents;";
    String LiteralContents = "Lnet/minecraft/network/chat/contents/PlainTextContents$LiteralContents;";
    String KeybindContents = "Lnet/minecraft/network/chat/contents/KeybindContents;";
    String FormattedText$ContentConsumer = "Lnet/minecraft/network/chat/FormattedText$ContentConsumer;";
    String DataComponentPatch = "Lnet/minecraft/core/component/DataComponentPatch;";
    String DataComponentPatchBuilder = "Lnet/minecraft/core/component/DataComponentPatch$Builder;";
    String ItemLore = "Lnet/minecraft/world/item/component/ItemLore;";
    String ItemEnchantments = "Lnet/minecraft/world/item/enchantment/ItemEnchantments;";
    String ItemEnchantmentsMutable = "Lnet/minecraft/world/item/enchantment/ItemEnchantments$Mutable;";
    String AdventureModePredicate = "Lnet/minecraft/world/item/AdventureModePredicate;";
    String ItemAttributeModifiers = "Lnet/minecraft/world/item/component/ItemAttributeModifiers;";
    String ItemAttributeModifiersBuilder = "Lnet/minecraft/world/item/component/ItemAttributeModifiers$Builder;";
    String AttributeModifier = "Lnet/minecraft/world/entity/ai/attributes/AttributeModifier;";
    String EquipmentSlotGroup = "Lnet/minecraft/world/entity/EquipmentSlotGroup;";
    String DyeItemColor = "Lnet/minecraft/world/item/component/DyedItemColor;";
    String ArmorTrim = "Lnet/minecraft/world/item/equipment/trim/ArmorTrim;";
    String Enchantment = "Lnet/minecraft/world/item/enchantment/Enchantment;";
    String SynchedEntityDataValue = "Lnet/minecraft/network/syncher/SynchedEntityData$DataValue;";
    String CraftEnchantment = "Lorg/bukkit/craftbukkit/enchantments/CraftEnchantment;";
    String MerchantOffer = "Lnet/minecraft/world/item/trading/MerchantOffer;";
    String MerchantOffers = "Lnet/minecraft/world/item/trading/MerchantOffers;";
    String ClientInformation ="Lnet/minecraft/server/level/ClientInformation;";
    String ChunkMapTrackedEntity = "Lnet/minecraft/server/level/ChunkMap$TrackedEntity;";
    String ServerPlayer = "Lnet/minecraft/server/level/ServerPlayer;";
    String SynchedEntityData = "Lnet/minecraft/network/syncher/SynchedEntityData;";
    String ChatFormatting = "Lnet/minecraft/ChatFormatting;";
    String ResourceKey = "Lnet/minecraft/resources/ResourceKey;";
    String Holder = "Lnet/minecraft/core/Holder;";
    String HolderLookupProvider = "Lnet/minecraft/core/HolderLookup$Provider;";
    String HolderReference = "Lnet/minecraft/core/Holder$Reference;";
    String CustomModelData ="Lnet/minecraft/world/item/component/CustomModelData;";
    String CraftCustomModelDataComponent ="Lorg/bukkit/craftbukkit/inventory/components/CraftCustomModelDataComponent;";
    String Enchantable ="Lnet/minecraft/world/item/component/Enchantable;";
    String ToggleTooltipsHelper = "Lnet/minecraft/world/level/storage/loot/functions/ToggleTooltips$ComponentToggle;";
    String TagKey = "Lnet/minecraft/tags/TagKey;";
    String CraftTag = "Lorg/bukkit/craftbukkit/tag/CraftTag;";
    String DataResult = "Lcom/mojang/serialization/DataResult;";
    String UseRemainder = "Lnet/minecraft/world/item/component/UseRemainder;";
    String UseCooldown = "Lnet/minecraft/world/item/component/UseCooldown;";
    String CraftUseCooldownComponent = "Lorg/bukkit/craftbukkit/inventory/components/CraftUseCooldownComponent;";
    String FoodProperties = "Lnet/minecraft/world/food/FoodProperties;";
    String CraftFoodComponent = "Lorg/bukkit/craftbukkit/inventory/components/CraftFoodComponent;";
    String Tool = "Lnet/minecraft/world/item/component/Tool;";
    String CraftToolComponent = "Lorg/bukkit/craftbukkit/inventory/components/CraftToolComponent;";
    String Equippable = "Lnet/minecraft/world/item/equipment/Equippable;";
    String CraftEquippableComponent = "Lorg/bukkit/craftbukkit/inventory/components/CraftEquippableComponent;";
    String JukeboxPlayable = "Lnet/minecraft/world/item/JukeboxPlayable;";
    String CraftJukeboxComponent = "Lorg/bukkit/craftbukkit/inventory/components/CraftJukeboxComponent;";
//    String Encoder = "Lcom/mojang/serialization/Encoder;";
//    String Encoder = "Lcom/mojang/serialization/Encoder;";
    String CraftMetaItem = "Lorg/bukkit/craftbukkit/inventory/CraftMetaItem;";
    String CraftAttributeInstance = "Lorg/bukkit/craftbukkit/attribute/CraftAttributeInstance;";
    String SnbtPrinterTagVisitor = "Lnet/minecraft/nbt/SnbtPrinterTagVisitor;";
    String TagVisitor = "Lnet/minecraft/nbt/TagVisitor;";
    String StringTagVisitor = "Lnet/minecraft/nbt/StringTagVisitor;";
    String TextComponentTagVisitor = "Lnet/minecraft/nbt/TextComponentTagVisitor;";
    String ItemContainerContents = "Lnet/minecraft/world/item/component/ItemContainerContents;";
    String TooltipDisplay = "Lnet/minecraft/world/item/component/TooltipDisplay;";
    String FontDescription = "Lnet/minecraft/network/chat/FontDescription;";
    String FontAtlasSprite= "Lnet/minecraft/network/chat/FontDescription$AtlasSprite;";
    String FontPlayerSprite = "Lnet/minecraft/network/chat/FontDescription$PlayerSprite;";
    String FontResource = "Lnet/minecraft/network/chat/FontDescription$Resource;";

    String ContainerClass = "net.minecraft.world.Container";
    String HopperBlockEntityClass = "net.minecraft.world.level.block.entity.HopperBlockEntity";
    String NbtCompoundClass = "net.minecraft.nbt.CompoundTag";
    String NumericTagClass = "net.minecraft.nbt.NumericTag";
    String CustomDataClass = "net.minecraft.world.item.component.CustomData";
    String UnbreakableClass = "net.minecraft.world.item.component.Unbreakable";
    String ChatComponentClass = "net.minecraft.network.chat.Component";
    String ItemLoreClass = "net.minecraft.world.item.component.ItemLore";


    String ChannelInitializeListenerClass = "io.papermc.paper.network.ChannelInitializeListener";
    String ChannelInitializeListenerHolderClass = "io.papermc.paper.network.ChannelInitializeListenerHolder";
    String PacketClass = "net.minecraft.network.protocol.Packet";
    String PacketListenerClass = "net.minecraft.network.PacketListener";
    String FriendlyByteBufClass = "net.minecraft.network.FriendlyByteBuf";
    String PacketSendListenerClass = "net.minecraft.network.PacketSendListener";

    public static Class<?> forName(String desName){
        try{
            return Class.forName(ByteCodeUtils.fromJvmType(desName));

        }catch (Throwable e){
            return null;
        }
    }
}
